#!/bin/bash

source /root/scripts/stackrc

function install_image {
  local name=$1
  local url=$2

  if [ ! -e /root/images/$name.qcow2 ]; then
    mkdir -p /root/images/
    curl -L -o /root/images/$name.qcow2 "$url"
  fi

  if ! glance index | grep "$name"; then
    glance add name=$name is_public=True protected=True disk_format=qcow2 container_format=bare < /root/images/$name.qcow2
  fi
}

{% for name, url in pillar['openstack']['glance']['default_images'].iteritems() %}
install_image {{ name }} "{{ url }}"
{% endfor %}
